#pretraining with SimSiam
pretraining:
  batch_size: 1
  learning_rate: 0.001 
  epochs: 10
  gpus: 0
  out_dim: 512
  pred_hidden_dim: 128
  proj_hidden_dim: 512
  num_ftrs: 512
  #input size of image
  input_size: 256
  log_interval: 5

finetuning:
  batch_size: 1
  learning_rate: 0.001
  epochs: 1
  gpus: 0
  log_interval: 5

UNet:
  # define the number of channels in the input, number of classes,
  channels: 1
  num_classes: 1
  dropout: 0.3












